#!/bin/sh

qt_path=
build_path=
# Empty paths will be filled automatically by searching for keywords.

printf "Running linter and dry-running formatter on source files\n"

res=0

#
# Run clang-tidy and clang-format on C and C++ files
#

if [ -z "$build_path" ];
then
    build_path=$(find . -wholename \*/build/* \
        | head -n 1 \
        | xargs realpath -m --relative-to=.)
fi

if [ -z "$build_path" ];
then
    printf "Aborting commit due to not finding the build directory. %s\n" \
        "Please check the path in the pre-commit file"
    exit 1
fi

for file in $(git diff-index --cached --name-only HEAD \
              | grep -iE '\.(c|cpp|h|hpp)$');
do
    if [ ! -e $file ];
    then
        continue
    fi

    # The checks are defined in the .clang-tidy config file, so they are not
    # passed as arguments.
    clang-tidy $file \
        -p $build_path \
        --warnings-as-errors=*
    res=$(( $res | $? ))

    clang-format $file \
        --style=InheritParentConfig \
        --dry-run \
        --Werror
    res=$(( $res | $? ))
done

#
# Output linting and formatting result
#

if [ $res -ne 0 ];
then
    printf "Aborting commit due to one or more warnings or an error\n"
    exit 1
fi

printf "Ok\n"
